polish mysql-create script

diff --git a/bin/mysql-create b/bin/mysql-create
--- a/bin/mysql-create
+++ b/bin/mysql-create
@@ -1,15 +1,29 @@
 #!/usr/bin/env bash
 
-# MYSQL_ROOT_USER and MYSQL_ROOT_PASS are defined in the "private" include.
-
 # First param is database name.
 DBNAME=$1
+
+# MYSQL_ROOT_USER and MYSQL_ROOT_PASS are defined in the "private" include.
+source "$HOME/.bash/private"
 
 if [ -n "$DBNAME" ]; then
   read -p "Create database: $DBNAME? (y/n) " RESP
 
   if [ "$RESP" = "y" ]; then
-    # @TODO make this more robust; check if db already exists, offer to truncate?
+    DBEXISTS=$(mysql -u$MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" --batch --skip-column-names -e "SHOW DATABASES LIKE '"$DBNAME"';" | grep "$DBNAME" > /dev/null; echo "$?");
+
+    if [ $DBEXISTS -eq 0 ];then
+      read -p "Database $DBNAME already exists, truncate it? (y/n) " RESP
+
+      if [ "$RESP" = "y" ]; then
+        mysql -u$MYSQL_ROOT_USER -p$MYSQL_ROOT_PASS -Nse "show tables '$DBNAME'" | while read table; do mysql -u$MYSQL_ROOT_USER -p$MYSQL_ROOT_PASS -e "drop table $table" $DBNAME; done
+        echo "Database truncated!"
+      else
+        echo "Script aborted."
+        exit;
+      fi
+    fi
+
     mysql -u$MYSQL_ROOT_USER -p$MYSQL_ROOT_PASS -Nse "CREATE DATABASE \`$DBNAME\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
     echo "Database created!"
   fi
